import { products } from './data/products.js';
import { normalizeText } from './utils/normalizeText.js';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const fallback='./assets/images/lihen_logo_transparente.webp';
const safe=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const img=p=>p?.images?.[0]||fallback;
const params=new URLSearchParams(location.search);
const state={q:params.get('q')||'',line:params.get('line')||'all',category:params.get('category')||'',status:params.get('status')||'',availability:params.get('availability')||'all',sort:params.get('sort')||'relevance',page:Math.max(1,Number(params.get('page'))||1),pageSize:12};
const activeFilter=$('[data-active-filter]');
const form=$('[data-search-form]'),input=$('#product-search'),grid=$('[data-search-grid]'),empty=$('[data-search-empty]'),count=$('[data-search-count]'),pagination=$('[data-search-pagination]');
if(input)input.value=state.q;
const priceNumber=p=>{const raw=String(p.price||'').replace(/[^0-9]/g,'');return raw?Number(raw):Number.MAX_SAFE_INTEGER};
const text=p=>normalizeText([p.name,p.brand,p.line,p.category,p.desc,p.color,p.availability,p.tag,p.searchText].filter(Boolean).join(' '));
const categoryAliases={labios:['labio','gloss','labial','tinta hidratante'],rostro:['rostro','facial','corrector','polvo compacto','papel matificante'],ojos:['ojos','pestanina','rizado'], 'cejas y pestanas':['cejas','pestanas','laminador'], 'cuidado facial':['cuidado facial','facial'], 'proteccion solar':['proteccion solar','protector solar','solar'],mascarillas:['mascarilla'], 'cuidado capilar':['cuidado capilar','shampoo','acondicionador','tonico','tratamiento capilar'],conjunto:['conjunto'],camiseta:['camiseta'],short:['short','pantaloneta'],casual:['vestido','casual'],tono:['tono','color'],accesorio:['accesorio','brocha','cosmetiquera','herramienta'],cosmetiquera:['cosmetiquera'], 'brocha herramienta':['brocha','herramienta'],rutina:['cuidado','rutina']};
function categoryMatches(product,category){if(!category)return true;const key=normalizeText(category);const haystack=text(product);const aliases=categoryAliases[key]||[key];return aliases.some(alias=>haystack.includes(normalizeText(alias)))}
function statusMatches(product,status){if(!status)return true;const haystack=text(product);if(status==='nuevo')return /nuevo|nuevo ingreso|reciente/.test(haystack);if(status==='restock')return /de nuevo|regres|restock/.test(haystack);if(status==='temporada')return /temporada|coleccion/.test(haystack);return haystack.includes(normalizeText(status))}
function filtered(){const q=normalizeText(state.q.trim());let list=products.map((p,i)=>({...p,_index:i})).filter(p=>!q||text(p).includes(q)).filter(p=>state.line==='all'||p.line===state.line).filter(p=>categoryMatches(p,state.category)).filter(p=>statusMatches(p,state.status)).filter(p=>state.availability==='all'||normalizeText(p.availability||p.tag||'').includes(normalizeText(state.availability)));if(state.sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'es'));else if(state.sort==='newest')list.sort((a,b)=>b._index-a._index);else if(state.sort==='price-low')list.sort((a,b)=>priceNumber(a)-priceNumber(b));else if(state.sort==='price-high')list.sort((a,b)=>priceNumber(b)-priceNumber(a));return list}
function priceDisclosure(product){const value=product?.price||'Precio por confirmar';return `<div class="price-disclosure"><strong>${safe(value)}</strong><small>Disponibilidad y precio final sujetos a confirmación</small></div>`}
function card(p){const second=p.images?.[1]||img(p);return `<article class="product-card search-product-card" data-product-id="${p.id}"><div class="product-image"><img class="primary" src="${img(p)}" alt="${safe(p.name)}" loading="lazy" decoding="async"><img class="secondary" data-secondary-src="${second}" alt="Otra vista de ${safe(p.name)}" loading="lazy" decoding="async"><div class="product-hover-actions"><button type="button" data-preview="${p.id}">Vista previa</button><button type="button" data-add="${p.id}">Agregar a mi selección</button></div></div><div class="product-info"><small>${safe(p.line)} · ${safe(p.brand)}</small><h3>${safe(p.name)}</h3>${priceDisclosure(p)}</div></article>`}
function syncUrl(){const url=new URL(location.href);[['q',state.q],['line',state.line==='all'?'':state.line],['category',state.category],['status',state.status],['availability',state.availability==='all'?'':state.availability],['sort',state.sort==='relevance'?'':state.sort],['page',state.page===1?'':String(state.page)]].forEach(([k,v])=>v?url.searchParams.set(k,v):url.searchParams.delete(k));history.replaceState({},'',url)}
function activeLabel(){return state.category||state.status||(state.line!=='all'?`Productos ${state.line}`:'Buscar productos')}
function render(){const list=filtered(),pages=Math.max(1,Math.ceil(list.length/state.pageSize));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.pageSize,view=list.slice(start,start+state.pageSize);grid.innerHTML=view.map(card).join('');empty.hidden=list.length>0;grid.hidden=list.length===0;count.textContent=`${list.length} resultado${list.length===1?'':'s'}`;pagination.innerHTML=list.length>state.pageSize?`${state.page>1?'<button data-page="prev" aria-label="Página anterior">‹</button>':''}${Array.from({length:pages},(_,i)=>`<button class="${i+1===state.page?'active':''}" data-page="${i+1}">${i+1}</button>`).join('')}${state.page<pages?'<button data-page="next" aria-label="Página siguiente">›</button>':''}`:'';$$('[data-search-line]').forEach(button=>button.classList.toggle('active',button.dataset.searchLine===state.line));const availability=$('[data-search-availability]'),sort=$('[data-search-sort]');if(availability)availability.value=state.availability;if(sort)sort.value=state.sort;const label=activeLabel();if(activeFilter){activeFilter.textContent=label;activeFilter.hidden=label==='Buscar productos'}document.title=`LIHEN.CO | ${label.charAt(0).toUpperCase()+label.slice(1)}`;syncUrl()}
form?.addEventListener('submit',e=>{e.preventDefault();state.q=input.value;state.page=1;render()});input?.addEventListener('input',()=>{state.q=input.value;state.page=1;render()});$$('[data-search-line]').forEach(b=>b.addEventListener('click',()=>{state.line=b.dataset.searchLine;state.page=1;render()}));$('[data-search-availability]')?.addEventListener('change',e=>{state.availability=e.target.value;state.page=1;render()});$('[data-search-sort]')?.addEventListener('change',e=>{state.sort=e.target.value;state.page=1;render()});grid?.addEventListener('click',event=>{const preview=event.target.closest('[data-preview]');const add=event.target.closest('[data-add]');if(preview){event.preventDefault();window.LIHENStorefront?.openProduct(preview.dataset.preview)}if(add){event.preventDefault();window.LIHENStorefront?.addProduct(add.dataset.add)}});
pagination?.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(!b)return;state.page=b.dataset.page==='prev'?state.page-1:b.dataset.page==='next'?state.page+1:Number(b.dataset.page);render();scrollTo({top:document.querySelector('.search-controls').offsetTop-120,behavior:'smooth'})});render();
