import { products } from './data/products.js';
import { normalizeText } from './utils/normalizeText.js';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const fallback='./assets/images/lihen_logo_transparente.webp';
const safe=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const img=p=>p?.images?.[0]||fallback;
const priceNumber=p=>{const m=String(p.price||'').replace(/[^0-9]/g,'');return m?Number(m):Number.MAX_SAFE_INTEGER};
const state={q:new URLSearchParams(location.search).get('q')||'',line:'all',availability:'all',sort:'relevance',page:1,pageSize:12};
const form=$('[data-search-form]'),input=$('#product-search'),grid=$('[data-search-grid]'),empty=$('[data-search-empty]'),count=$('[data-search-count]'),pagination=$('[data-search-pagination]');
if(input)input.value=state.q;
function searchable(p){return normalizeText([p.name,p.brand,p.line,p.category,p.desc,p.color,p.availability,p.tag].filter(Boolean).join(' '))}
function filtered(){const q=normalizeText(state.q.trim());let list=products.map((p,i)=>({...p,_index:i,_score:q?searchable(p).includes(q)?0:99:0})).filter(p=>!q||searchable(p).includes(q)).filter(p=>state.line==='all'||p.line===state.line).filter(p=>state.availability==='all'||normalizeText(p.availability||p.tag||'').includes(state.availability));if(state.sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'es'));else if(state.sort==='newest')list.sort((a,b)=>b._index-a._index);else if(state.sort==='price-low')list.sort((a,b)=>priceNumber(a)-priceNumber(b));else if(state.sort==='price-high')list.sort((a,b)=>priceNumber(b)-priceNumber(a));return list}
function card(p){const second=p.images?.[1]||img(p);return `<article class="product-card search-product-card"><div class="product-image"><span class="tag">${safe(p.tag||p.availability||'Disponible')}</span><img class="primary" src="${img(p)}" alt="${safe(p.name)}" loading="lazy"><img class="secondary" src="${second}" alt="Otra vista de ${safe(p.name)}" loading="lazy"><div class="product-hover-actions"><button type="button" data-preview="${p.id}">Vista previa</button><button type="button" data-add="${p.id}">Agregar a mi selección</button></div></div><div class="product-info"><small>${safe(p.line)} · ${safe(p.brand)}</small><h3>${safe(p.name)}</h3><p>${safe((p.desc||'').slice(0,96))}${(p.desc||'').length>96?'…':''}</p><strong>${safe(p.price||'Por confirmar')}</strong></div></article>`}
function render(){const list=filtered();const pages=Math.max(1,Math.ceil(list.length/state.pageSize));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.pageSize;const view=list.slice(start,start+state.pageSize);grid.innerHTML=view.map(card).join('');empty.hidden=list.length>0;grid.hidden=list.length===0;count.textContent=`${list.length} resultado${list.length===1?'':'s'}`;pagination.innerHTML=list.length>state.pageSize?`${state.page>1?'<button data-page="prev" aria-label="Página anterior">‹</button>':''}${Array.from({length:pages},(_,i)=>`<button class="${i+1===state.page?'active':''}" data-page="${i+1}">${i+1}</button>`).join('')}${state.page<pages?'<button data-page="next" aria-label="Página siguiente">›</button>':''}`:'';const u=new URL(location.href);state.q?u.searchParams.set('q',state.q):u.searchParams.delete('q');history.replaceState({},'',u)}
form?.addEventListener('submit',e=>{e.preventDefault();state.q=input.value;state.page=1;render()});input?.addEventListener('input',()=>{state.q=input.value;state.page=1;render()});$$('[data-search-line]').forEach(b=>b.addEventListener('click',()=>{$$('[data-search-line]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.line=b.dataset.searchLine;state.page=1;render()}));$('[data-search-availability]')?.addEventListener('change',e=>{state.availability=e.target.value;state.page=1;render()});$('[data-search-sort]')?.addEventListener('change',e=>{state.sort=e.target.value;state.page=1;render()});pagination?.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(!b)return;state.page=b.dataset.page==='prev'?state.page-1:b.dataset.page==='next'?state.page+1:Number(b.dataset.page);render();scrollTo({top:document.querySelector('.search-controls').offsetTop-120,behavior:'smooth'})});render();
