import { getLocalParticipant } from "../../repositories/participantRepository.js";
import { getMyRewards,getWinnerRanking,claimReward,subscribeToRewards } from "../../repositories/rewardRepository.js";
import { buildRewardClaimMessage,openRewardClaimWhatsApp } from "../../services/rewardWhatsAppService.js";
const $=s=>document.querySelector(s);let participant=null,rewards=[];
const gameLabel=k=>({trivia:"Trivia",word:"Palabra",flash:"Reto",roulette:"Ruleta"}[k]||k);
function renderRewards(){const box=$("#my-rewards-list");if(!box)return;box.innerHTML=rewards.length?rewards.map(r=>`<article class="reward-item" data-reward-id="${r.id}"><div><span>${gameLabel(r.game_key)}</span><strong>${r.reward_label}</strong><small>Código: ${r.claim_code} · ${r.claim_status}</small></div><button class="button button-primary" type="button" data-claim-reward ${r.claim_status==='delivered'||r.claim_status==='cancelled'?'disabled':''}>${r.claim_status==='pending'?'Reclamar por WhatsApp':'Ver mensaje'}</button></article>`).join(""):"<p>Aún no tienes recompensas registradas.</p>";}
async function renderRanking(){const list=$("#winner-ranking");if(!list)return;try{const rows=await getWinnerRanking();const grouped=[];const seen=new Set();for(const r of rows){if(seen.has(r.participant_public_id))continue;seen.add(r.participant_public_id);grouped.push(r);}list.innerHTML=grouped.length?grouped.slice(0,12).map((r,i)=>`<li><strong>${i+1}. ${r.display_name}</strong><span>${r.total_rewards} recompensa${r.total_rewards===1?'':'s'} · ${r.modality}</span></li>`).join(""):"<li>El ranking aparecerá cuando haya ganadores.</li>";}catch(e){list.innerHTML="<li>No fue posible cargar el ranking.</li>";}}
async function loadMine(){if(!participant)return;try{rewards=await getMyRewards(participant.id,participant.accessCode);renderRewards();}catch(e){console.warn(e);}}
export async function initParticipantRewards(){participant=getLocalParticipant();await Promise.all([loadMine(),renderRanking()]);$("#my-rewards-list")?.addEventListener("click",async e=>{const btn=e.target.closest("[data-claim-reward]");if(!btn)return;const id=btn.closest("[data-reward-id]").dataset.rewardId;let reward=rewards.find(r=>r.id===id);try{if(reward.claim_status==='pending')reward=await claimReward({publicId:participant.id,accessCode:participant.accessCode,rewardId:id});const message=buildRewardClaimMessage(reward,participant);await openRewardClaimWhatsApp(message);await loadMine();}catch(err){window.alert(err.message||"No fue posible preparar la reclamación.");}});await subscribeToRewards(()=>{loadMine();renderRanking();});}
