import { getLocalParticipant } from "../../repositories/participantRepository.js";
import { getCurrentRouletteRound,spinRoulette,subscribeToRouletteRounds } from "../../repositories/rouletteRepository.js";
import { getRouletteSegments } from "../../data/roulettePrizes.js";
import { paintRouletteWheel,rotationForSegment,spinWheel } from "../../utils/rouletteAnimation.js";
const $=s=>document.querySelector(s);const segments=getRouletteSegments();let participant=null,round=null,currentRotation=0,busy=false,lastAnimatedRound=null;
function setMessage(text,type="info"){const el=$("#roulette-message");if(el){el.textContent=text;el.dataset.type=type;}}
async function animateResult(next){if(!next?.result_segment_index||lastAnimatedRound===next.id)return;lastAnimatedRound=next.id;currentRotation=rotationForSegment(Number(next.result_segment_index),segments.length,currentRotation);busy=true;$("[data-roulette-spin]").disabled=true;setMessage("La ruleta está girando…");await spinWheel($("#roulette-wheel"),currentRotation);busy=false;setMessage(next.result_label?`Resultado: ${next.result_label}`:"Giro finalizado.",next.is_winner?"success":"info");render(next);}
function render(next){round=next;const card=$("#roulette-participant");if(!card)return;card.hidden=!round;$("#roulette-round-status").textContent=!round?"En espera":round.status==="open"?"Ruleta habilitada":round.status==="spun"?"Giro finalizado":"Ruleta cerrada";$("#roulette-active-name").textContent=round?.active_display_name||"Esperando participante activo";const ownTurn=Boolean(participant&&round?.active_participant_public_id===participant.id);const canSpin=Boolean(ownTurn&&round?.status==="open"&&!round?.result_prize_key&&!busy);$("[data-roulette-spin]").disabled=!canSpin;if(!round)setMessage("La administradora abrirá la ruleta.");else if(round.result_label)setMessage(`Resultado: ${round.result_label}`,round.is_winner?"success":"info");else if(canSpin)setMessage("Es tu turno. Pulsa el botón una sola vez para girar.","success");else if(round.status==="open")setMessage("Observa el giro. Solo la persona activa puede usar la ruleta.");else setMessage("La ruleta está cerrada.");if(round?.result_segment_index!=null)animateResult(round);}
async function spin(){if(!participant||!round||busy)return;busy=true;$("[data-roulette-spin]").disabled=true;setMessage("Reservando el resultado de forma segura…");try{const result=await spinRoulette({participantId:participant.id,accessCode:participant.accessCode,roundId:round.id});round={...round,...result};await animateResult(round);}catch(error){busy=false;setMessage(error.message||"No fue posible girar la ruleta.","error");render(round);}}
export async function initParticipantRoulette(){participant=getLocalParticipant();paintRouletteWheel($("#roulette-wheel"),segments);$("[data-roulette-spin]")?.addEventListener("click",spin);try{render(await getCurrentRouletteRound())}catch(e){console.warn(e)}await subscribeToRouletteRounds(async()=>render(await getCurrentRouletteRound()));}
