import { getLocalParticipant } from "../../repositories/participantRepository.js";
import { getCurrentWordRound,submitWordAnswer,subscribeToWordRounds } from "../../repositories/wordGameRepository.js";
import { createWordTicker,formatWordTime } from "../../utils/wordTimer.js";
const $=s=>document.querySelector(s);let round=null,room=null,participant=null,answered=null,unsub=()=>{},stop=()=>{};
function myTurn(){return participant&&room&&String(room.active_participant_public_id||"")===String(participant.id||"");}
function render(r){round=r;const card=$("#word-participant");if(!card)return;const open=r?.status==="open",can=open&&myTurn()&&answered!==r.id;card.hidden=!r;$("#word-round-status").textContent=open?"Ronda abierta":r?.status==="closed"?"Ronda cerrada":"En espera";$("#word-hint").textContent=r?.hint_text||"La administradora publicará una pista.";$("#word-mask").textContent=r?.masked_word||"_ _ _ _ _";$("#word-answer").disabled=!can;$("#word-submit").disabled=!can;$("#word-message").textContent=!r?"Espera las indicaciones.":open&&!myTurn()?"Observa la pista. Solo responde quien tiene el turno activo.":r.status==="closed"?(r.winner_display_name?`Ganó: ${r.winner_display_name}.`:`La ronda terminó sin respuesta correcta.`):can?"Escribe la palabra antes de que termine el tiempo.":"Respuesta registrada.";}
async function submit(e){e.preventDefault();if(!round||!myTurn()||answered===round.id)return;const input=$("#word-answer"),message=$("#word-message");message.textContent="Validando respuesta…";input.disabled=true;$("#word-submit").disabled=true;try{const result=await submitWordAnswer({participantId:participant.id,accessCode:participant.accessCode,roundId:round.id,answer:input.value});answered=round.id;message.textContent=result?.is_correct?"¡Palabra correcta! El resultado quedó sincronizado.":"La palabra no es correcta. Espera la siguiente indicación.";}catch(error){input.disabled=!myTurn();$("#word-submit").disabled=!myTurn();message.textContent=error.message||"No fue posible registrar la respuesta.";}}
export function updateWordRoomState(next){room=next;render(round);}
export async function initParticipantWordGame(){participant=getLocalParticipant();$("#word-form")?.addEventListener("submit",submit);try{render(await getCurrentWordRound());}catch(e){console.warn(e)}unsub=await subscribeToWordRounds(async()=>{try{render(await getCurrentWordRound())}catch(e){console.warn(e)}});stop=createWordTicker(()=>round,s=>{const el=$("#word-clock");if(el)el.textContent=formatWordTime(s)});return()=>{unsub();stop()};}
