-- LIHEN.CO · Invitaciones privadas · Supabase
-- Ejecutar en SQL Editor. Revisar antes de producción.
create table if not exists public.invitations (
  id bigint generated by default as identity primary key,
  access_code text not null unique,
  responsible text not null,
  display_name text not null,
  named_guests integer not null default 1 check (named_guests between 1 and 3),
  max_attendees integer not null default 3 check (max_attendees between 1 and 3),
  phone text,
  notes text,
  attendance_mode text check (attendance_mode in ('presencial','virtual','no_asiste')),
  confirmed_attendees integer,
  confirmed_at timestamptz,
  created_at timestamptz not null default now()
);

-- La ubicación real se conserva únicamente en Supabase.
-- No escriba la dirección ni el enlace de Maps dentro del HTML o JavaScript público.
create table if not exists public.invitation_private_event_config (
  id smallint primary key default 1 check (id = 1),
  event_address text not null,
  maps_url text not null,
  updated_at timestamptz not null default now()
);

alter table public.invitations enable row level security;
alter table public.invitation_private_event_config enable row level security;
revoke all on public.invitations from anon, authenticated;
revoke all on public.invitation_private_event_config from anon, authenticated;

create or replace function public.get_invitation_by_code(p_code text)
returns table(access_code text,responsible text,display_name text,named_guests integer,max_attendees integer,status text)
language sql security definer set search_path=public as $$
  select i.access_code,i.responsible,i.display_name,i.named_guests,i.max_attendees,
         case when i.confirmed_at is null then 'pending' else 'confirmed' end
  from public.invitations i where upper(i.access_code)=upper(trim(p_code)) limit 1;
$$;

create or replace function public.confirm_invitation(p_code text,p_mode text,p_attendees integer)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  inv public.invitations;
  private_config public.invitation_private_event_config;
  location_payload jsonb := null;
begin
  select * into inv from public.invitations where upper(access_code)=upper(trim(p_code)) for update;
  if inv.id is null then raise exception 'Invitación no encontrada'; end if;
  if p_mode not in ('presencial','virtual','no_asiste') then raise exception 'Modalidad inválida'; end if;
  if p_mode='presencial' and (p_attendees<inv.named_guests or p_attendees>inv.max_attendees) then raise exception 'Cantidad fuera del cupo autorizado'; end if;

  update public.invitations
     set attendance_mode=p_mode,
         confirmed_attendees=case when p_mode='presencial' then p_attendees else 0 end,
         confirmed_at=now()
   where id=inv.id;

  if p_mode='presencial' then
    select * into private_config from public.invitation_private_event_config where id=1;
    if private_config.id is not null then
      location_payload := jsonb_build_object(
        'address', private_config.event_address,
        'maps_url', private_config.maps_url
      );
    end if;
  end if;

  return jsonb_build_object(
    'ok', true,
    'mode', p_mode,
    'location', location_payload
  );
end;$$;

grant execute on function public.get_invitation_by_code(text) to anon;
grant execute on function public.confirm_invitation(text,text,integer) to anon;

-- CONFIGURACIÓN PRIVADA OBLIGATORIA
-- Ejecute este INSERT manualmente en Supabase y reemplace los valores.
-- No copie la dirección real en archivos que se subirán a GitHub.
-- insert into public.invitation_private_event_config(id,event_address,maps_url)
-- values (1,'DIRECCIÓN REAL','ENLACE PRIVADO DE GOOGLE MAPS')
-- on conflict (id) do update set
--   event_address=excluded.event_address,
--   maps_url=excluded.maps_url,
--   updated_at=now();
