import { FLASH_CHALLENGES } from "../data/flashChallenges.js";
import { getCurrentFlashRound, subscribeToFlashRounds, subscribeToFlashSubmissions } from "../repositories/flashChallengeRepository.js";
import { openFlashRound,closeFlashRound,resetFlashRound,getFlashSubmissions,reviewFlashSubmission } from "../repositories/adminFlashChallengeRepository.js";
import { createFlashTicker,formatFlashTime } from "../utils/flashTimer.js";
const $=s=>document.querySelector(s);let round=null;
function message(text,type="info"){const el=$("[data-flash-admin-message]");el.textContent=text;el.dataset.type=type;el.hidden=false;}
function escapeHtml(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
async function render(next){round=next;$("#flash-admin-state").textContent=round?.status||"waiting";$("#flash-admin-title").textContent=round?.title||"No hay un reto activo";$("#flash-admin-participant").textContent=round?.active_display_name?`Participante: ${round.active_display_name}`:"Sin participante activo";const submissions=round?.id?await getFlashSubmissions(round.id):[];$("#flash-admin-submissions").innerHTML=submissions.length?submissions.map(item=>`<li data-flash-submission="${item.id}"><div><strong>${escapeHtml(item.display_name)}</strong><span>${escapeHtml(item.modality)} · ${item.review_status}</span></div><div class="flash-review-actions"><button type="button" class="button button-primary" data-flash-review="approved">Aprobar</button><button type="button" class="button button-secondary" data-flash-review="rejected">No aprobar</button></div></li>`).join(""):"<li>Sin reportes registrados.</li>";}
export async function initAdminFlashChallenge(){const select=$("#flash-challenge-select");select.innerHTML=FLASH_CHALLENGES.map(c=>`<option value="${c.key}">${c.position}. ${c.title}</option>`).join("");$("[data-flash-open]").addEventListener("click",async()=>{try{await openFlashRound(select.value,$("#flash-duration").value);await render(await getCurrentFlashRound());message("Reto publicado para el participante activo.","success")}catch(e){message(e.message,"error")}});$("[data-flash-close]").addEventListener("click",async()=>{try{await closeFlashRound();await render(await getCurrentFlashRound());message("Reto cerrado.","success")}catch(e){message(e.message,"error")}});$("[data-flash-reset]").addEventListener("click",async()=>{try{await resetFlashRound();await render(null);message("Reto relámpago reiniciado.","success")}catch(e){message(e.message,"error")}});$("#flash-admin-submissions").addEventListener("click",async event=>{const button=event.target.closest("[data-flash-review]");if(!button)return;const item=button.closest("[data-flash-submission]");try{await reviewFlashSubmission(item.dataset.flashSubmission,button.dataset.flashReview);await render(await getCurrentFlashRound());message(button.dataset.flashReview==="approved"?"Reto aprobado y resultado sincronizado.":"Reto marcado como no aprobado.","success")}catch(e){message(e.message,"error")}});try{await render(await getCurrentFlashRound())}catch(e){console.warn(e)}await subscribeToFlashRounds(async()=>render(await getCurrentFlashRound()));await subscribeToFlashSubmissions(async()=>render(await getCurrentFlashRound()));createFlashTicker(()=>round,s=>{$("#flash-admin-clock").textContent=formatFlashTime(s)});}
