import { getContingencyStatus,closeAllRounds,releaseStuckTurn,requeueParticipants,reopenEventAccess,recoverRoomSoft,resetOperationalState,listContingencyLogs } from "../repositories/adminContingencyRepository.js";
const $=s=>document.querySelector(s);
const labels={close:"Cerrar todas las rondas",release:"Liberar turno atascado",requeue:"Reconstruir colas",reopen:"Reabrir acceso",recover:"Recuperación suave",reset:"Reinicio operativo"};
function message(text,type="info"){const el=$("[data-contingency-message]");el.textContent=text;el.dataset.type=type;el.hidden=false;}
function metric(label,value,danger=false){return `<article class="contingency-metric${danger?" contingency-metric--danger":""}"><span>${label}</span><strong>${value}</strong></article>`;}
function renderStatus(s){if(!s)return;const open=Number(s.trivia_open)+Number(s.word_open)+Number(s.vote_open)+Number(s.flash_open)+Number(s.roulette_open);$("#contingency-status-grid").innerHTML=[metric("Sala",s.room_open?"Abierta":"Cerrada",!s.room_open),metric("Registro",s.registration_open?"Abierto":"Cerrado"),metric("Turno",s.turn_status||"idle",s.turn_status!=="idle"&&Number(s.participants_active)!==1),metric("Participantes activos",s.participants_active,Number(s.participants_active)>1),metric("Rondas abiertas",open,open>1),metric("En espera",s.participants_waiting)].join("");$("#contingency-checked-at").textContent=`Última revisión: ${new Date(s.checked_at).toLocaleString("es-CO")}`;}
function renderLogs(logs){$("#contingency-log-list").innerHTML=logs.length?logs.map(l=>`<li><strong>${l.action_key}</strong><span>${l.admin_name||"Administración"} · ${new Date(l.created_at).toLocaleString("es-CO")}</span><code>${JSON.stringify(l.details||{})}</code></li>`).join(""):"<li>Sin acciones de contingencia registradas.</li>";}
async function refresh(){renderStatus(await getContingencyStatus());renderLogs(await listContingencyLogs());}
async function run(action,key,needsStrongConfirmation=false){const text=needsStrongConfirmation?`Esta acción realizará: ${labels[key]}. No borra el historial, pero cambiará el estado operativo. Escribe REINICIAR para continuar.`:`¿Confirmas la acción: ${labels[key]}?`;if(needsStrongConfirmation){const value=prompt(text);if(value!=="REINICIAR")return;}else if(!confirm(text))return;document.querySelectorAll("[data-contingency-action]").forEach(b=>b.disabled=true);try{await action();message(`${labels[key]} completada correctamente.`,"success");await refresh();document.dispatchEvent(new CustomEvent("lihen:contingency-complete"));}catch(error){message(error.message||"No fue posible ejecutar la contingencia.","error");}finally{document.querySelectorAll("[data-contingency-action]").forEach(b=>b.disabled=false);}}
export async function initAdminContingency(){await refresh();$("[data-contingency-refresh]").addEventListener("click",refresh);$("[data-contingency-close]").addEventListener("click",()=>run(closeAllRounds,"close"));$("[data-contingency-release]").addEventListener("click",()=>run(()=>releaseStuckTurn("waiting"),"release"));$("[data-contingency-requeue]").addEventListener("click",()=>run(requeueParticipants,"requeue"));$("[data-contingency-reopen]").addEventListener("click",()=>run(reopenEventAccess,"reopen"));$("[data-contingency-recover]").addEventListener("click",()=>run(recoverRoomSoft,"recover"));$("[data-contingency-reset]").addEventListener("click",()=>run(resetOperationalState,"reset",true));}
