import { VOTE_POLLS } from "../data/votePolls.js";
import { getCurrentVoteRound, getVoteRanking, subscribeToVoteRounds, subscribeToVotes } from "../repositories/voteRepository.js";
import { openVoteRound, closeVoteRound, resetVoteRound, getVoteParticipants } from "../repositories/adminVoteRepository.js";
import { createVoteTicker, formatVoteTime } from "../utils/voteTimer.js";
const $=selector=>document.querySelector(selector);let round=null;
function message(text,type="info"){const el=$("[data-vote-admin-message]");el.textContent=text;el.dataset.type=type;el.hidden=false;}
function escapeHtml(value="") { return String(value).replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char])); }
async function render(next){round=next;$("#vote-admin-state").textContent=round?.status||"waiting";$("#vote-admin-question").textContent=round?.question_text||"No hay una votación activa";const ranking=round?.id?await getVoteRanking(round.id):[];const votes=round?.id?await getVoteParticipants(round.id):[];$("#vote-admin-total").textContent=`${votes.length} voto${votes.length===1?"":"s"}`;$("#vote-admin-ranking").innerHTML=ranking.length?ranking.map((row,index)=>`<li><strong>${index+1}. ${escapeHtml(row.option_label)}</strong><span>${row.vote_count} voto${Number(row.vote_count)===1?"":"s"}</span></li>`).join(""):"<li>Sin votos registrados.</li>";$("#vote-admin-voters").innerHTML=votes.length?votes.map(vote=>`<li><strong>${escapeHtml(vote.display_name)}</strong><span>${escapeHtml(vote.option_label)}</span><small>${vote.modality}</small></li>`).join(""):"<li>Sin participantes que hayan votado.</li>";}
export async function initAdminVoteGame(){const select=$("#vote-poll-select");select.innerHTML=VOTE_POLLS.map(poll=>`<option value="${poll.key}">${poll.position}. ${poll.question}</option>`).join("");$("[data-vote-open]").addEventListener("click",async()=>{try{await openVoteRound(select.value,$("#vote-duration").value);await render(await getCurrentVoteRound());message("Votación publicada para todas las personas registradas.","success")}catch(error){message(error.message,"error")}});$("[data-vote-close]").addEventListener("click",async()=>{try{await closeVoteRound();await render(await getCurrentVoteRound());message("Votación cerrada.","success")}catch(error){message(error.message,"error")}});$("[data-vote-reset]").addEventListener("click",async()=>{try{await resetVoteRound();await render(null);message("Votación reiniciada.","success")}catch(error){message(error.message,"error")}});try{await render(await getCurrentVoteRound())}catch(error){console.warn(error)}await subscribeToVoteRounds(async()=>render(await getCurrentVoteRound()));await subscribeToVotes(async()=>render(round));createVoteTicker(()=>round,seconds=>{$("#vote-admin-clock").textContent=formatVoteTime(seconds)});}
