-- Etapa 7 · Tabla pública para recibir solicitudes de contacto.
-- Ejecutar en Supabase > SQL Editor.

create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  public_id uuid not null unique,
  full_name text not null check (char_length(full_name) between 2 and 80),
  email text not null check (char_length(email) <= 120),
  phone text,
  city text,
  preferred_channel text not null check (preferred_channel in ('whatsapp', 'email')),
  subject text not null check (char_length(subject) <= 80),
  message text not null check (char_length(message) between 15 and 800),
  accepted_privacy boolean not null check (accepted_privacy = true),
  client_created_at timestamptz,
  created_at timestamptz not null default now(),
  status text not null default 'new' check (status in ('new', 'in_review', 'answered', 'closed'))
);

alter table public.contact_requests enable row level security;

-- El visitante puede crear una solicitud, pero no leer, modificar ni borrar registros.
drop policy if exists "Public can create contact requests" on public.contact_requests;
create policy "Public can create contact requests"
on public.contact_requests
for insert
to anon, authenticated
with check (accepted_privacy = true);

-- No se crea política SELECT pública. Los datos deben revisarse desde el panel seguro de Supabase.
create index if not exists contact_requests_created_at_idx
  on public.contact_requests (created_at desc);
