-- ETAPA 9: base para inauguración, registro y futura sala Realtime.
create table if not exists public.event_rooms (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  title text not null,
  registration_open boolean not null default true,
  room_open boolean not null default false,
  registration_closes_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.event_participants (
  id bigint generated by default as identity primary key,
  public_id uuid unique not null,
  room_id uuid references public.event_rooms(id) on delete cascade,
  full_name text not null check (char_length(full_name) between 3 and 70),
  email text not null,
  display_name text not null check (char_length(display_name) between 2 and 30),
  modality text not null check (modality in ('presencial','virtual')),
  accepted_rules boolean not null check (accepted_rules = true),
  access_code text unique not null,
  registration_status text not null default 'registered' check (registration_status in ('registered','connected','waiting','active','winner','disabled','left')),
  registered_order bigint generated by default as identity,
  connected_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.event_rooms enable row level security;
alter table public.event_participants enable row level security;

-- El visitante puede registrar su propia participación, pero no listar participantes.
drop policy if exists "public can register event participant" on public.event_participants;
create policy "public can register event participant" on public.event_participants
for insert to anon, authenticated with check (accepted_rules = true);

-- Los administradores autorizados de la etapa 8 pueden leer y gestionar la sala.
drop policy if exists "admins can read event participants" on public.event_participants;
create policy "admins can read event participants" on public.event_participants
for select to authenticated using (exists(select 1 from public.admin_profiles ap where ap.user_id=auth.uid() and ap.is_active=true));

drop policy if exists "admins can update event participants" on public.event_participants;
create policy "admins can update event participants" on public.event_participants
for update to authenticated using (exists(select 1 from public.admin_profiles ap where ap.user_id=auth.uid() and ap.is_active=true)) with check (exists(select 1 from public.admin_profiles ap where ap.user_id=auth.uid() and ap.is_active=true));

insert into public.event_rooms(slug,title) values ('inauguracion-lihen','Inauguración LIHEN.CO') on conflict (slug) do nothing;
