-- ETAPA 12: Trivia LIHEN con pregunta pública, respuesta privada y validación en servidor.

create table if not exists public.event_trivia_questions (
  id bigint generated by default as identity primary key,
  question_key text unique not null,
  question_text text not null,
  options jsonb not null check (jsonb_typeof(options)='array' and jsonb_array_length(options) between 2 and 6),
  position integer not null default 1,
  is_active boolean not null default true
);

create table if not exists public.event_trivia_answers (
  question_id bigint primary key references public.event_trivia_questions(id) on delete cascade,
  correct_option integer not null check (correct_option between 0 and 5)
);

create table if not exists public.event_trivia_rounds (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.event_rooms(id) on delete cascade,
  question_id bigint not null references public.event_trivia_questions(id),
  status text not null default 'waiting' check (status in ('waiting','open','closed')),
  opened_at timestamptz,
  closes_at timestamptz,
  duration_seconds integer not null default 25 check (duration_seconds between 10 and 90),
  winner_participant_id bigint references public.event_participants(id) on delete set null,
  winner_display_name text,
  created_at timestamptz not null default now(),
  closed_at timestamptz
);

create table if not exists public.event_trivia_responses (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.event_trivia_rounds(id) on delete cascade,
  participant_id bigint not null references public.event_participants(id) on delete cascade,
  selected_option integer not null check (selected_option between 0 and 5),
  is_correct boolean not null,
  response_ms integer,
  answered_at timestamptz not null default now(),
  unique(round_id,participant_id)
);

alter table public.event_trivia_questions enable row level security;
alter table public.event_trivia_answers enable row level security;
alter table public.event_trivia_rounds enable row level security;
alter table public.event_trivia_responses enable row level security;

create or replace view public.event_trivia_questions_public as
select id,question_key,question_text,options,position,is_active from public.event_trivia_questions;

create or replace view public.event_trivia_rounds_public as
select r.id,er.slug as room_slug,r.status,r.opened_at,r.closes_at,r.duration_seconds,r.winner_display_name,r.created_at,r.closed_at,
       q.question_key,q.question_text,q.options
from public.event_trivia_rounds r
join public.event_rooms er on er.id=r.room_id
join public.event_trivia_questions q on q.id=r.question_id;

create or replace view public.event_trivia_responses_admin as
select tr.id,tr.round_id,tr.selected_option,tr.is_correct,tr.response_ms,tr.answered_at,ep.display_name,ep.modality
from public.event_trivia_responses tr join public.event_participants ep on ep.id=tr.participant_id;

grant select on public.event_trivia_questions_public to anon,authenticated;
grant select on public.event_trivia_rounds_public to anon,authenticated;
grant select on public.event_trivia_responses_admin to authenticated;

create policy "admins manage trivia questions" on public.event_trivia_questions for all to authenticated
using (public.is_active_event_admin()) with check (public.is_active_event_admin());
create policy "admins read trivia answers" on public.event_trivia_answers for select to authenticated using (public.is_active_event_admin());
create policy "public reads trivia rounds" on public.event_trivia_rounds for select to anon,authenticated using (true);
create policy "admins manage trivia rounds" on public.event_trivia_rounds for all to authenticated
using (public.is_active_event_admin()) with check (public.is_active_event_admin());
create policy "admins read trivia responses" on public.event_trivia_responses for select to authenticated using (public.is_active_event_admin());

insert into public.event_trivia_questions(question_key,question_text,options,position) values
('identidad-luz','¿Qué representa la letra L en LIHEN.CO?','["Liderazgo","Luz","Libertad","Lealtad"]',1),
('identidad-integridad','¿Qué valor representa la letra I en LIHEN.CO?','["Innovación","Inspiración","Integridad","Imaginación"]',2),
('lineas-marca','¿Cuáles son las dos líneas principales del catálogo LIHEN.CO?','["Beauty Care y Style","Moda y Hogar","Cosmética y Tecnología","Accesorios y Alimentos"]',3),
('consulta-productos','¿Cuál es el canal preparado en la web para consultar productos?','["Telegram","Correo postal","WhatsApp","Llamada internacional"]',4),
('proposito-excelencia','¿Qué representa la letra E en LIHEN.CO?','["Economía","Elegancia","Excelencia","Estrategia"]',5)
on conflict(question_key) do update set question_text=excluded.question_text,options=excluded.options,position=excluded.position;

insert into public.event_trivia_answers(question_id,correct_option)
select id,case question_key when 'identidad-luz' then 1 when 'identidad-integridad' then 2 when 'lineas-marca' then 0 when 'consulta-productos' then 2 when 'proposito-excelencia' then 2 end
from public.event_trivia_questions
on conflict(question_id) do update set correct_option=excluded.correct_option;

create or replace function public.open_event_trivia_round(p_question_key text,p_duration_seconds integer default 25)
returns public.event_trivia_rounds language plpgsql security definer set search_path=public as $$
declare v_room public.event_rooms;v_question public.event_trivia_questions;v_round public.event_trivia_rounds;
begin
 if not public.is_active_event_admin() then raise exception 'Acceso administrativo requerido'; end if;
 select * into v_room from public.event_rooms where slug='inauguracion-lihen';
 select * into v_question from public.event_trivia_questions where question_key=p_question_key and is_active=true;
 if v_question.id is null then raise exception 'Pregunta no encontrada'; end if;
 update public.event_trivia_rounds set status='closed',closed_at=now() where room_id=v_room.id and status='open';
 p_duration_seconds:=greatest(10,least(coalesce(p_duration_seconds,25),90));
 insert into public.event_trivia_rounds(room_id,question_id,status,opened_at,closes_at,duration_seconds)
 values(v_room.id,v_question.id,'open',now(),now()+make_interval(secs=>p_duration_seconds),p_duration_seconds) returning * into v_round;
 update public.event_rooms set active_activity='Trivia LIHEN',updated_at=now() where id=v_room.id;
 return v_round;
end;$$;

create or replace function public.close_event_trivia_round() returns public.event_trivia_rounds
language plpgsql security definer set search_path=public as $$
declare v_round public.event_trivia_rounds;begin
 if not public.is_active_event_admin() then raise exception 'Acceso administrativo requerido'; end if;
 update public.event_trivia_rounds set status='closed',closed_at=now() where id=(select id from public.event_trivia_rounds order by created_at desc limit 1) returning * into v_round;return v_round;end;$$;

create or replace function public.reset_event_trivia_round() returns boolean
language plpgsql security definer set search_path=public as $$begin
 if not public.is_active_event_admin() then raise exception 'Acceso administrativo requerido'; end if;
 delete from public.event_trivia_rounds where room_id=(select id from public.event_rooms where slug='inauguracion-lihen');return true;end;$$;

create or replace function public.submit_event_trivia_answer(p_public_id uuid,p_access_code text,p_round_id bigint,p_selected_option integer)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_round public.event_trivia_rounds;v_participant public.event_participants;v_correct integer;v_is_correct boolean;v_response public.event_trivia_responses;
begin
 select * into v_round from public.event_trivia_rounds where id=p_round_id for update;
 if v_round.id is null or v_round.status<>'open' or now()>v_round.closes_at then raise exception 'La ronda no está abierta'; end if;
 select ep.* into v_participant from public.event_participants ep join public.event_rooms er on er.active_participant_id=ep.id
 where ep.public_id=p_public_id and ep.access_code=p_access_code and er.id=v_round.room_id and ep.registration_status='active';
 if v_participant.id is null then raise exception 'Solo el participante con el turno activo puede responder'; end if;
 select correct_option into v_correct from public.event_trivia_answers where question_id=v_round.question_id;
 v_is_correct:=p_selected_option=v_correct;
 insert into public.event_trivia_responses(round_id,participant_id,selected_option,is_correct,response_ms)
 values(v_round.id,v_participant.id,p_selected_option,v_is_correct,greatest(0,floor(extract(epoch from(now()-v_round.opened_at))*1000)::integer))
 returning * into v_response;
 if v_is_correct and v_round.winner_participant_id is null then
  update public.event_trivia_rounds set winner_participant_id=v_participant.id,winner_display_name=v_participant.display_name,status='closed',closed_at=now() where id=v_round.id;
 end if;
 return jsonb_build_object('ok',true,'is_correct',v_is_correct,'response_ms',v_response.response_ms);
exception when unique_violation then raise exception 'Ya respondiste esta ronda';end;$$;

revoke all on function public.open_event_trivia_round(text,integer) from public;revoke all on function public.close_event_trivia_round() from public;revoke all on function public.reset_event_trivia_round() from public;revoke all on function public.submit_event_trivia_answer(uuid,text,bigint,integer) from public;
grant execute on function public.open_event_trivia_round(text,integer) to authenticated;grant execute on function public.close_event_trivia_round() to authenticated;grant execute on function public.reset_event_trivia_round() to authenticated;grant execute on function public.submit_event_trivia_answer(uuid,text,bigint,integer) to anon,authenticated;

do $$ begin alter publication supabase_realtime add table public.event_trivia_rounds;exception when duplicate_object then null;end $$;
