-- ETAPA 13: Encuentra la palabra con pista pública y respuesta privada.
create table if not exists public.event_word_challenges(
 id bigint generated by default as identity primary key,
 challenge_key text unique not null,
 hint_text text not null,
 masked_word text not null,
 position integer not null default 1,
 is_active boolean not null default true
);
create table if not exists public.event_word_answers(
 challenge_id bigint primary key references public.event_word_challenges(id) on delete cascade,
 normalized_answer text not null
);
create table if not exists public.event_word_rounds(
 id bigint generated by default as identity primary key,
 room_id uuid not null references public.event_rooms(id) on delete cascade,
 challenge_id bigint not null references public.event_word_challenges(id),
 status text not null default 'waiting' check(status in('waiting','open','closed')),
 opened_at timestamptz,closes_at timestamptz,duration_seconds integer not null default 30 check(duration_seconds between 10 and 120),
 winner_participant_id bigint references public.event_participants(id) on delete set null,winner_display_name text,
 created_at timestamptz not null default now(),closed_at timestamptz
);
create table if not exists public.event_word_attempts(
 id bigint generated by default as identity primary key,
 round_id bigint not null references public.event_word_rounds(id) on delete cascade,
 participant_id bigint not null references public.event_participants(id) on delete cascade,
 submitted_answer text not null,is_correct boolean not null,response_ms integer,answered_at timestamptz not null default now(),
 unique(round_id,participant_id)
);
alter table public.event_word_challenges enable row level security;alter table public.event_word_answers enable row level security;alter table public.event_word_rounds enable row level security;alter table public.event_word_attempts enable row level security;
create or replace view public.event_word_rounds_public as
select r.id,er.slug room_slug,r.status,r.opened_at,r.closes_at,r.duration_seconds,r.winner_display_name,r.created_at,r.closed_at,c.challenge_key,c.hint_text,c.masked_word
from public.event_word_rounds r join public.event_rooms er on er.id=r.room_id join public.event_word_challenges c on c.id=r.challenge_id;
create or replace view public.event_word_attempts_admin as
select a.id,a.round_id,a.submitted_answer,a.is_correct,a.response_ms,a.answered_at,p.display_name,p.modality
from public.event_word_attempts a join public.event_participants p on p.id=a.participant_id;
grant select on public.event_word_rounds_public to anon,authenticated;grant select on public.event_word_attempts_admin to authenticated;
create policy "admins manage word challenges" on public.event_word_challenges for all to authenticated using(public.is_active_event_admin()) with check(public.is_active_event_admin());
create policy "admins read word answers" on public.event_word_answers for select to authenticated using(public.is_active_event_admin());
create policy "public reads word rounds" on public.event_word_rounds for select to anon,authenticated using(true);
create policy "admins manage word rounds" on public.event_word_rounds for all to authenticated using(public.is_active_event_admin()) with check(public.is_active_event_admin());
create policy "admins read word attempts" on public.event_word_attempts for select to authenticated using(public.is_active_event_admin());
insert into public.event_word_challenges(challenge_key,hint_text,masked_word,position) values
('luz','Valor de LIHEN.CO que inspira, guía y refleja buenas obras.','L _ Z',1),
('integridad','Actuar con verdad, transparencia y coherencia.','I _ T _ G R _ D _ D',2),
('honra','Tomar decisiones para agradar primero a Dios y servir correctamente.','H _ N R _',3),
('excelencia','Servir con amor, orden y responsabilidad.','E X C _ L _ N C _ A',4),
('nobleza','Crecer sin vanidad, manipulación, orgullo ni desorden.','N _ B L _ Z _',5)
on conflict(challenge_key) do update set hint_text=excluded.hint_text,masked_word=excluded.masked_word,position=excluded.position;
insert into public.event_word_answers(challenge_id,normalized_answer)
select id,challenge_key from public.event_word_challenges on conflict(challenge_id) do update set normalized_answer=excluded.normalized_answer;
create or replace function public.normalize_event_word(p_text text) returns text language sql immutable as $$select lower(regexp_replace(translate(trim(coalesce(p_text,'')),'áéíóúüñÁÉÍÓÚÜÑ','aeiouunAEIOUUN'),'[^a-zA-Z0-9]','','g'));$$;
create or replace function public.open_event_word_round(p_challenge_key text,p_duration_seconds integer default 30) returns public.event_word_rounds language plpgsql security definer set search_path=public as $$declare v_room public.event_rooms;v_challenge public.event_word_challenges;v_round public.event_word_rounds;begin if not public.is_active_event_admin() then raise exception 'Acceso administrativo requerido';end if;select * into v_room from public.event_rooms where slug='inauguracion-lihen';select * into v_challenge from public.event_word_challenges where challenge_key=p_challenge_key and is_active=true;if v_challenge.id is null then raise exception 'Reto no encontrado';end if;update public.event_word_rounds set status='closed',closed_at=now() where room_id=v_room.id and status='open';p_duration_seconds:=greatest(10,least(coalesce(p_duration_seconds,30),120));insert into public.event_word_rounds(room_id,challenge_id,status,opened_at,closes_at,duration_seconds) values(v_room.id,v_challenge.id,'open',now(),now()+make_interval(secs=>p_duration_seconds),p_duration_seconds) returning * into v_round;update public.event_rooms set active_activity='Encuentra la palabra',updated_at=now() where id=v_room.id;return v_round;end;$$;
create or replace function public.close_event_word_round() returns public.event_word_rounds language plpgsql security definer set search_path=public as $$declare v_round public.event_word_rounds;begin if not public.is_active_event_admin() then raise exception 'Acceso administrativo requerido';end if;update public.event_word_rounds set status='closed',closed_at=now() where id=(select id from public.event_word_rounds order by created_at desc limit 1) returning * into v_round;return v_round;end;$$;
create or replace function public.reset_event_word_round() returns boolean language plpgsql security definer set search_path=public as $$begin if not public.is_active_event_admin() then raise exception 'Acceso administrativo requerido';end if;delete from public.event_word_rounds where room_id=(select id from public.event_rooms where slug='inauguracion-lihen');return true;end;$$;
create or replace function public.submit_event_word_answer(p_public_id uuid,p_access_code text,p_round_id bigint,p_answer text) returns jsonb language plpgsql security definer set search_path=public as $$declare v_round public.event_word_rounds;v_participant public.event_participants;v_correct text;v_is_correct boolean;v_attempt public.event_word_attempts;begin select * into v_round from public.event_word_rounds where id=p_round_id for update;if v_round.id is null or v_round.status<>'open' or now()>v_round.closes_at then raise exception 'La ronda no está abierta';end if;select ep.* into v_participant from public.event_participants ep join public.event_rooms er on er.active_participant_id=ep.id where ep.public_id=p_public_id and ep.access_code=p_access_code and er.id=v_round.room_id and ep.registration_status='active';if v_participant.id is null then raise exception 'Solo el participante con el turno activo puede responder';end if;select normalized_answer into v_correct from public.event_word_answers where challenge_id=v_round.challenge_id;v_is_correct:=public.normalize_event_word(p_answer)=public.normalize_event_word(v_correct);insert into public.event_word_attempts(round_id,participant_id,submitted_answer,is_correct,response_ms) values(v_round.id,v_participant.id,left(trim(p_answer),80),v_is_correct,greatest(0,floor(extract(epoch from(now()-v_round.opened_at))*1000)::integer)) returning * into v_attempt;if v_is_correct and v_round.winner_participant_id is null then update public.event_word_rounds set winner_participant_id=v_participant.id,winner_display_name=v_participant.display_name,status='closed',closed_at=now() where id=v_round.id;end if;return jsonb_build_object('ok',true,'is_correct',v_is_correct,'response_ms',v_attempt.response_ms);exception when unique_violation then raise exception 'Ya respondiste esta ronda';end;$$;
revoke all on function public.open_event_word_round(text,integer) from public;revoke all on function public.close_event_word_round() from public;revoke all on function public.reset_event_word_round() from public;revoke all on function public.submit_event_word_answer(uuid,text,bigint,text) from public;
grant execute on function public.open_event_word_round(text,integer) to authenticated;grant execute on function public.close_event_word_round() to authenticated;grant execute on function public.reset_event_word_round() to authenticated;grant execute on function public.submit_event_word_answer(uuid,text,bigint,text) to anon,authenticated;
do $$begin alter publication supabase_realtime add table public.event_word_rounds;exception when duplicate_object then null;end$$;
