-- ETAPA 14: Vota tu favorito con participación simultánea y ranking público en tiempo real.
create table if not exists public.event_vote_polls(
 id bigint generated by default as identity primary key,
 poll_key text unique not null,
 question_text text not null,
 position integer not null default 1,
 is_active boolean not null default true
);
create table if not exists public.event_vote_options(
 id bigint generated by default as identity primary key,
 poll_id bigint not null references public.event_vote_polls(id) on delete cascade,
 option_key text not null,
 option_label text not null,
 option_description text,
 position integer not null default 1,
 unique(poll_id,option_key)
);
create table if not exists public.event_vote_rounds(
 id bigint generated by default as identity primary key,
 room_id uuid not null references public.event_rooms(id) on delete cascade,
 poll_id bigint not null references public.event_vote_polls(id),
 status text not null default 'waiting' check(status in('waiting','open','closed')),
 opened_at timestamptz,
 closes_at timestamptz,
 duration_seconds integer not null default 45 check(duration_seconds between 10 and 300),
 created_at timestamptz not null default now(),
 closed_at timestamptz
);
create table if not exists public.event_votes(
 id bigint generated by default as identity primary key,
 round_id bigint not null references public.event_vote_rounds(id) on delete cascade,
 participant_id bigint not null references public.event_participants(id) on delete cascade,
 option_id bigint not null references public.event_vote_options(id),
 voted_at timestamptz not null default now(),
 unique(round_id,participant_id)
);
alter table public.event_vote_polls enable row level security;
alter table public.event_vote_options enable row level security;
alter table public.event_vote_rounds enable row level security;
alter table public.event_votes enable row level security;

create or replace view public.event_vote_rounds_public as
select r.id,er.slug room_slug,r.status,r.opened_at,r.closes_at,r.duration_seconds,r.created_at,r.closed_at,p.poll_key,p.question_text,
 coalesce(jsonb_agg(jsonb_build_object('key',o.option_key,'label',o.option_label,'description',o.option_description,'position',o.position) order by o.position) filter(where o.id is not null),'[]'::jsonb) options
from public.event_vote_rounds r
join public.event_rooms er on er.id=r.room_id
join public.event_vote_polls p on p.id=r.poll_id
left join public.event_vote_options o on o.poll_id=p.id
group by r.id,er.slug,p.id;

create or replace view public.event_vote_ranking_public as
select r.id round_id,o.option_key,o.option_label,o.position option_position,count(v.id)::integer vote_count
from public.event_vote_rounds r
join public.event_vote_options o on o.poll_id=r.poll_id
left join public.event_votes v on v.round_id=r.id and v.option_id=o.id
group by r.id,o.id;

create or replace view public.event_votes_admin as
select v.id,v.round_id,v.voted_at,p.display_name,p.modality,o.option_key,o.option_label
from public.event_votes v
join public.event_participants p on p.id=v.participant_id
join public.event_vote_options o on o.id=v.option_id;

grant select on public.event_vote_rounds_public to anon,authenticated;
grant select on public.event_vote_ranking_public to anon,authenticated;
grant select on public.event_votes_admin to authenticated;
create policy "public reads vote polls" on public.event_vote_polls for select to anon,authenticated using(true);
create policy "admins manage vote polls" on public.event_vote_polls for all to authenticated using(public.is_active_event_admin()) with check(public.is_active_event_admin());
create policy "public reads vote options" on public.event_vote_options for select to anon,authenticated using(true);
create policy "admins manage vote options" on public.event_vote_options for all to authenticated using(public.is_active_event_admin()) with check(public.is_active_event_admin());
create policy "public reads vote rounds" on public.event_vote_rounds for select to anon,authenticated using(true);
create policy "admins manage vote rounds" on public.event_vote_rounds for all to authenticated using(public.is_active_event_admin()) with check(public.is_active_event_admin());
create policy "admins read votes" on public.event_votes for select to authenticated using(public.is_active_event_admin());

insert into public.event_vote_polls(poll_key,question_text,position) values
('favorite-line','¿Cuál línea de LIHEN.CO te representa más?',1),
('favorite-value','¿Qué valor de LIHEN.CO conecta más contigo?',2),
('favorite-experience','¿Qué experiencia te gustaría vivir primero con LIHEN.CO?',3)
on conflict(poll_key) do update set question_text=excluded.question_text,position=excluded.position;

insert into public.event_vote_options(poll_id,option_key,option_label,option_description,position)
select p.id,x.option_key,x.option_label,x.option_description,x.position
from public.event_vote_polls p join (values
('favorite-line','beauty-care','Beauty Care','Belleza, cuidado personal y detalles que resaltan tu esencia.',1),
('favorite-line','style','Style','Moda, accesorios y elementos para expresar tu estilo.',2),
('favorite-value','luz','Luz','Inspirar, guiar y reflejar buenas obras.',1),
('favorite-value','integridad','Integridad','Actuar con verdad, transparencia y coherencia.',2),
('favorite-value','excelencia','Excelencia','Servir con amor, orden y responsabilidad.',3),
('favorite-value','nobleza','Nobleza','Crecer cuidando a las personas y evitando la vanidad.',4),
('favorite-experience','asesoria','Asesoría personalizada','Recibir orientación según mis gustos y necesidades.',1),
('favorite-experience','novedades','Conocer novedades','Descubrir productos, colecciones y lanzamientos.',2),
('favorite-experience','eventos','Participar en eventos','Vivir experiencias presenciales y virtuales.',3)
) as x(poll_key,option_key,option_label,option_description,position) on x.poll_key=p.poll_key
on conflict(poll_id,option_key) do update set option_label=excluded.option_label,option_description=excluded.option_description,position=excluded.position;

create or replace function public.open_event_vote_round(p_poll_key text,p_duration_seconds integer default 45)
returns public.event_vote_rounds language plpgsql security definer set search_path=public as $$
declare v_room public.event_rooms;v_poll public.event_vote_polls;v_round public.event_vote_rounds;
begin
 if not public.is_active_event_admin() then raise exception 'Acceso administrativo requerido';end if;
 select * into v_room from public.event_rooms where slug='inauguracion-lihen';
 select * into v_poll from public.event_vote_polls where poll_key=p_poll_key and is_active=true;
 if v_poll.id is null then raise exception 'Votación no encontrada';end if;
 update public.event_vote_rounds set status='closed',closed_at=now() where room_id=v_room.id and status='open';
 p_duration_seconds:=greatest(10,least(coalesce(p_duration_seconds,45),300));
 insert into public.event_vote_rounds(room_id,poll_id,status,opened_at,closes_at,duration_seconds) values(v_room.id,v_poll.id,'open',now(),now()+make_interval(secs=>p_duration_seconds),p_duration_seconds) returning * into v_round;
 update public.event_rooms set active_activity='Vota tu favorito',updated_at=now() where id=v_room.id;
 return v_round;
end;$$;

create or replace function public.close_event_vote_round() returns public.event_vote_rounds language plpgsql security definer set search_path=public as $$
declare v_round public.event_vote_rounds;begin
 if not public.is_active_event_admin() then raise exception 'Acceso administrativo requerido';end if;
 update public.event_vote_rounds set status='closed',closed_at=now() where id=(select id from public.event_vote_rounds order by created_at desc limit 1) returning * into v_round;
 return v_round;
end;$$;

create or replace function public.reset_event_vote_round() returns boolean language plpgsql security definer set search_path=public as $$
begin
 if not public.is_active_event_admin() then raise exception 'Acceso administrativo requerido';end if;
 delete from public.event_vote_rounds where room_id=(select id from public.event_rooms where slug='inauguracion-lihen');
 return true;
end;$$;

create or replace function public.submit_event_vote(p_public_id uuid,p_access_code text,p_round_id bigint,p_option_key text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_round public.event_vote_rounds;v_participant public.event_participants;v_option public.event_vote_options;v_vote public.event_votes;
begin
 select * into v_round from public.event_vote_rounds where id=p_round_id for update;
 if v_round.id is null or v_round.status<>'open' or now()>v_round.closes_at then raise exception 'La votación no está abierta';end if;
 select * into v_participant from public.event_participants where public_id=p_public_id and access_code=p_access_code and room_id=v_round.room_id and registration_status not in('disabled','left');
 if v_participant.id is null then raise exception 'El registro del participante no es válido';end if;
 select * into v_option from public.event_vote_options where poll_id=v_round.poll_id and option_key=p_option_key;
 if v_option.id is null then raise exception 'La opción seleccionada no es válida';end if;
 insert into public.event_votes(round_id,participant_id,option_id) values(v_round.id,v_participant.id,v_option.id) returning * into v_vote;
 return jsonb_build_object('ok',true,'vote_id',v_vote.id);
exception when unique_violation then raise exception 'Ya registraste tu voto en esta ronda';end;$$;

revoke all on function public.open_event_vote_round(text,integer) from public;
revoke all on function public.close_event_vote_round() from public;
revoke all on function public.reset_event_vote_round() from public;
revoke all on function public.submit_event_vote(uuid,text,bigint,text) from public;
grant execute on function public.open_event_vote_round(text,integer) to authenticated;
grant execute on function public.close_event_vote_round() to authenticated;
grant execute on function public.reset_event_vote_round() to authenticated;
grant execute on function public.submit_event_vote(uuid,text,bigint,text) to anon,authenticated;
do $$begin alter publication supabase_realtime add table public.event_vote_rounds;exception when duplicate_object then null;end$$;
do $$begin alter publication supabase_realtime add table public.event_votes;exception when duplicate_object then null;end$$;
