-- ETAPA 15: Reto relámpago con turno individual y validación administrativa.
create table if not exists public.event_flash_challenges(
 id bigint generated by default as identity primary key,
 challenge_key text unique not null,
 title text not null,
 instruction_text text not null,
 completion_label text not null default 'Ya completé el reto',
 position integer not null default 1,
 is_active boolean not null default true
);
create table if not exists public.event_flash_rounds(
 id bigint generated by default as identity primary key,
 room_id uuid not null references public.event_rooms(id) on delete cascade,
 challenge_id bigint not null references public.event_flash_challenges(id),
 active_participant_id bigint references public.event_participants(id) on delete set null,
 status text not null default 'waiting' check(status in('waiting','open','closed')),
 opened_at timestamptz, closes_at timestamptz,
 duration_seconds integer not null default 30 check(duration_seconds between 10 and 180),
 review_status text not null default 'pending' check(review_status in('pending','approved','rejected')),
 reviewed_participant_id bigint references public.event_participants(id) on delete set null,
 reviewed_display_name text,
 reviewed_at timestamptz,
 created_at timestamptz not null default now(), closed_at timestamptz
);
create table if not exists public.event_flash_submissions(
 id bigint generated by default as identity primary key,
 round_id bigint not null references public.event_flash_rounds(id) on delete cascade,
 participant_id bigint not null references public.event_participants(id) on delete cascade,
 submitted_at timestamptz not null default now(),
 review_status text not null default 'pending' check(review_status in('pending','approved','rejected')),
 review_note text,
 reviewed_at timestamptz,
 reviewed_by uuid references auth.users(id) on delete set null,
 unique(round_id,participant_id)
);
alter table public.event_flash_challenges enable row level security;
alter table public.event_flash_rounds enable row level security;
alter table public.event_flash_submissions enable row level security;

create or replace view public.event_flash_rounds_public as
select r.id,er.slug room_slug,r.status,r.opened_at,r.closes_at,r.duration_seconds,r.review_status,
 r.reviewed_display_name,r.created_at,r.closed_at,c.challenge_key,c.title,c.instruction_text,c.completion_label,
 p.public_id active_participant_public_id,p.display_name active_display_name,
 exists(select 1 from public.event_flash_submissions s where s.round_id=r.id) has_submission
from public.event_flash_rounds r
join public.event_rooms er on er.id=r.room_id
join public.event_flash_challenges c on c.id=r.challenge_id
left join public.event_participants p on p.id=r.active_participant_id;
create or replace view public.event_flash_submissions_admin as
select s.id,s.round_id,s.submitted_at,s.review_status,s.review_note,s.reviewed_at,p.display_name,p.modality
from public.event_flash_submissions s join public.event_participants p on p.id=s.participant_id;
grant select on public.event_flash_rounds_public to anon,authenticated;
grant select on public.event_flash_submissions_admin to authenticated;

create policy "admins manage flash challenges" on public.event_flash_challenges for all to authenticated using(public.is_active_event_admin()) with check(public.is_active_event_admin());
create policy "public reads flash rounds" on public.event_flash_rounds for select to anon,authenticated using(true);
create policy "admins manage flash rounds" on public.event_flash_rounds for all to authenticated using(public.is_active_event_admin()) with check(public.is_active_event_admin());
create policy "admins read flash submissions" on public.event_flash_submissions for select to authenticated using(public.is_active_event_admin());

insert into public.event_flash_challenges(challenge_key,title,instruction_text,completion_label,position) values
('presenta-favorito','Presenta tu favorito','Elige un producto o categoría de LIHEN.CO y explica en una frase por qué te gusta.','Ya presenté mi favorito',1),
('valor-en-accion','Valor en acción','Menciona un valor de LIHEN.CO y da un ejemplo breve de cómo aplicarlo en la vida diaria.','Ya compartí mi ejemplo',2),
('frase-creativa','Frase creativa','Crea una frase corta que incluya las palabras LIHEN, estilo y propósito.','Ya dije mi frase',3),
('recomendacion-express','Recomendación exprés','Recomienda en menos de 20 segundos una experiencia de LIHEN.CO a otra persona.','Ya hice mi recomendación',4),
('gesto-lihen','Gesto LIHEN','Haz un gesto o pose elegante que represente la esencia de LIHEN.CO frente a la cámara o al público.','Ya realicé el reto',5)
on conflict(challenge_key) do update set title=excluded.title,instruction_text=excluded.instruction_text,completion_label=excluded.completion_label,position=excluded.position;

create or replace function public.open_event_flash_round(p_challenge_key text,p_duration_seconds integer default 30)
returns public.event_flash_rounds language plpgsql security definer set search_path=public as $$
declare v_room public.event_rooms;v_challenge public.event_flash_challenges;v_round public.event_flash_rounds;
begin
 if not public.is_active_event_admin() then raise exception 'Acceso administrativo requerido';end if;
 select * into v_room from public.event_rooms where slug='inauguracion-lihen' for update;
 if v_room.active_participant_id is null then raise exception 'Primero debes activar el turno de un participante';end if;
 select * into v_challenge from public.event_flash_challenges where challenge_key=p_challenge_key and is_active=true;
 if v_challenge.id is null then raise exception 'Reto no encontrado';end if;
 update public.event_flash_rounds set status='closed',closed_at=now() where room_id=v_room.id and status='open';
 p_duration_seconds:=greatest(10,least(coalesce(p_duration_seconds,30),180));
 insert into public.event_flash_rounds(room_id,challenge_id,active_participant_id,status,opened_at,closes_at,duration_seconds)
 values(v_room.id,v_challenge.id,v_room.active_participant_id,'open',now(),now()+make_interval(secs=>p_duration_seconds),p_duration_seconds) returning * into v_round;
 update public.event_rooms set active_activity='Reto relámpago',updated_at=now() where id=v_room.id;
 return v_round;
end;$$;
create or replace function public.close_event_flash_round() returns public.event_flash_rounds language plpgsql security definer set search_path=public as $$
declare v_round public.event_flash_rounds;begin if not public.is_active_event_admin() then raise exception 'Acceso administrativo requerido';end if;update public.event_flash_rounds set status='closed',closed_at=now() where id=(select id from public.event_flash_rounds order by created_at desc limit 1) returning * into v_round;return v_round;end;$$;
create or replace function public.reset_event_flash_round() returns boolean language plpgsql security definer set search_path=public as $$begin if not public.is_active_event_admin() then raise exception 'Acceso administrativo requerido';end if;delete from public.event_flash_rounds where room_id=(select id from public.event_rooms where slug='inauguracion-lihen');return true;end;$$;
create or replace function public.submit_event_flash_completion(p_public_id uuid,p_access_code text,p_round_id bigint) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_round public.event_flash_rounds;v_participant public.event_participants;v_submission public.event_flash_submissions;
begin
 select * into v_round from public.event_flash_rounds where id=p_round_id for update;
 if v_round.id is null or v_round.status<>'open' or now()>v_round.closes_at then raise exception 'La ronda no está abierta';end if;
 select * into v_participant from public.event_participants where public_id=p_public_id and access_code=p_access_code and id=v_round.active_participant_id and registration_status='active';
 if v_participant.id is null then raise exception 'Solo el participante con el turno activo puede registrar el reto';end if;
 insert into public.event_flash_submissions(round_id,participant_id) values(v_round.id,v_participant.id) returning * into v_submission;
 return jsonb_build_object('ok',true,'submission_id',v_submission.id,'review_status','pending');
exception when unique_violation then raise exception 'Ya reportaste este reto';end;$$;
create or replace function public.review_event_flash_submission(p_submission_id bigint,p_decision text,p_note text default '') returns jsonb language plpgsql security definer set search_path=public as $$
declare v_submission public.event_flash_submissions;v_participant public.event_participants;
begin
 if not public.is_active_event_admin() then raise exception 'Acceso administrativo requerido';end if;
 if p_decision not in('approved','rejected') then raise exception 'Decisión no válida';end if;
 select * into v_submission from public.event_flash_submissions where id=p_submission_id for update;
 if v_submission.id is null then raise exception 'Reporte no encontrado';end if;
 select * into v_participant from public.event_participants where id=v_submission.participant_id;
 update public.event_flash_submissions set review_status=p_decision,review_note=nullif(trim(p_note),''),reviewed_at=now(),reviewed_by=auth.uid() where id=p_submission_id;
 update public.event_flash_rounds set review_status=p_decision,reviewed_participant_id=v_participant.id,reviewed_display_name=v_participant.display_name,reviewed_at=now(),status='closed',closed_at=now() where id=v_submission.round_id;
 if p_decision='approved' then update public.event_participants set registration_status='winner' where id=v_participant.id;end if;
 return jsonb_build_object('ok',true,'decision',p_decision,'participant',v_participant.display_name);
end;$$;
revoke all on function public.open_event_flash_round(text,integer) from public;
revoke all on function public.close_event_flash_round() from public;
revoke all on function public.reset_event_flash_round() from public;
revoke all on function public.submit_event_flash_completion(uuid,text,bigint) from public;
revoke all on function public.review_event_flash_submission(bigint,text,text) from public;
grant execute on function public.open_event_flash_round(text,integer) to authenticated;
grant execute on function public.close_event_flash_round() to authenticated;
grant execute on function public.reset_event_flash_round() to authenticated;
grant execute on function public.submit_event_flash_completion(uuid,text,bigint) to anon,authenticated;
grant execute on function public.review_event_flash_submission(bigint,text,text) to authenticated;
do $$begin alter publication supabase_realtime add table public.event_flash_rounds;exception when duplicate_object then null;end$$;
do $$begin alter publication supabase_realtime add table public.event_flash_submissions;exception when duplicate_object then null;end$$;
