-- Etapa 16: Ruleta LIHEN con resultado atómico e inventario protegido.
create table if not exists public.event_roulette_inventory (
 id bigint generated by default as identity primary key,
 room_id bigint not null references public.event_rooms(id) on delete cascade,
 prize_key text not null,
 label text not null,
 position integer not null,
 initial_stock integer,
 remaining_stock integer,
 weight integer not null default 1 check(weight > 0),
 is_winner boolean not null default true,
 active boolean not null default true,
 unique(room_id, prize_key)
);
create table if not exists public.event_roulette_rounds (
 id uuid primary key default gen_random_uuid(), room_id bigint not null references public.event_rooms(id) on delete cascade,
 active_participant_id bigint references public.event_participants(id), status text not null default 'open' check(status in ('open','spun','closed')),
 result_prize_key text, result_label text, result_segment_index integer, is_winner boolean not null default false,
 opened_at timestamptz not null default now(), spun_at timestamptz, created_at timestamptz not null default now()
);
create table if not exists public.event_roulette_spins (
 id uuid primary key default gen_random_uuid(), round_id uuid not null references public.event_roulette_rounds(id) on delete cascade,
 participant_id bigint not null references public.event_participants(id), prize_key text not null, prize_label text not null,
 segment_index integer not null, is_winner boolean not null default false, created_at timestamptz not null default now(), unique(round_id), unique(round_id,participant_id)
);
alter table public.event_roulette_inventory enable row level security;
alter table public.event_roulette_rounds enable row level security;
alter table public.event_roulette_spins enable row level security;
insert into public.event_roulette_inventory(room_id,prize_key,label,position,initial_stock,remaining_stock,weight,is_winner)
select r.id,x.prize_key,x.label,x.position,x.stock,x.stock,x.weight,x.is_winner from public.event_rooms r cross join (values
 ('discount_10','10% de descuento',0,5,2,true),('sweet','Dulce',1,10,3,true),('try_again','Sigue intentando',2,null,4,false),
 ('gift','Obsequio',3,6,2,true),('discount_15','15% de descuento',4,5,1,true),('try_again_2','Sigue intentando',5,null,4,false)
) as x(prize_key,label,position,stock,weight,is_winner) where r.slug='inauguracion-lihen'
on conflict(room_id,prize_key) do nothing;
create or replace view public.event_roulette_rounds_public as
select rr.id,r.slug room_slug,rr.status,p.public_id active_participant_public_id,p.display_name active_display_name,
 rr.result_prize_key,rr.result_label,rr.result_segment_index,rr.is_winner,rr.opened_at,rr.spun_at,rr.created_at
from public.event_roulette_rounds rr join public.event_rooms r on r.id=rr.room_id left join public.event_participants p on p.id=rr.active_participant_id;
create or replace view public.event_roulette_inventory_public as
select r.slug room_slug,i.prize_key,i.label,i.position,i.initial_stock,i.remaining_stock,(i.initial_stock is null) unlimited,i.active
from public.event_roulette_inventory i join public.event_rooms r on r.id=i.room_id;
create or replace view public.event_roulette_spins_admin as
select s.*,p.display_name,p.modality from public.event_roulette_spins s join public.event_participants p on p.id=s.participant_id;
grant select on public.event_roulette_rounds_public,public.event_roulette_inventory_public to anon,authenticated;
grant select on public.event_roulette_spins_admin to authenticated;
create or replace function public.open_event_roulette_round(p_room_slug text default 'inauguracion-lihen') returns public.event_roulette_rounds language plpgsql security definer set search_path=public as $$
declare v_room public.event_rooms; v_round public.event_roulette_rounds;
begin if not public.is_event_admin(auth.uid()) then raise exception 'Acceso no autorizado'; end if;
 select * into v_room from event_rooms where slug=p_room_slug; if v_room.active_participant_id is null then raise exception 'Primero activa un participante'; end if;
 update event_roulette_rounds set status='closed' where room_id=v_room.id and status='open';
 insert into event_roulette_rounds(room_id,active_participant_id) values(v_room.id,v_room.active_participant_id) returning * into v_round; return v_round; end $$;
create or replace function public.close_event_roulette_round(p_room_slug text default 'inauguracion-lihen') returns public.event_roulette_rounds language plpgsql security definer set search_path=public as $$
declare v public.event_roulette_rounds; begin if not public.is_event_admin(auth.uid()) then raise exception 'Acceso no autorizado'; end if; update event_roulette_rounds rr set status='closed' from event_rooms r where rr.room_id=r.id and r.slug=p_room_slug and rr.status in('open','spun') returning rr.* into v; return v; end $$;
create or replace function public.reset_event_roulette_round(p_room_slug text default 'inauguracion-lihen') returns boolean language plpgsql security definer set search_path=public as $$ begin if not public.is_event_admin(auth.uid()) then raise exception 'Acceso no autorizado'; end if; delete from event_roulette_rounds using event_rooms r where event_roulette_rounds.room_id=r.id and r.slug=p_room_slug; return true; end $$;
create or replace function public.reset_event_roulette_inventory(p_room_slug text default 'inauguracion-lihen') returns boolean language plpgsql security definer set search_path=public as $$ begin if not public.is_event_admin(auth.uid()) then raise exception 'Acceso no autorizado'; end if; update event_roulette_inventory i set remaining_stock=initial_stock from event_rooms r where i.room_id=r.id and r.slug=p_room_slug; return true; end $$;
create or replace function public.update_event_roulette_inventory(p_room_slug text,p_prize_key text,p_stock integer) returns boolean language plpgsql security definer set search_path=public as $$ begin if not public.is_event_admin(auth.uid()) then raise exception 'Acceso no autorizado'; end if; if p_stock<0 then raise exception 'El stock no puede ser negativo'; end if; update event_roulette_inventory i set remaining_stock=p_stock from event_rooms r where i.room_id=r.id and r.slug=p_room_slug and i.prize_key=p_prize_key and i.initial_stock is not null; return found; end $$;
create or replace function public.spin_event_roulette(p_public_id uuid,p_access_code text,p_round_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_round event_roulette_rounds;v_participant event_participants;v_prize event_roulette_inventory;v_total int;v_pick int;
begin
 select * into v_round from event_roulette_rounds where id=p_round_id for update; if v_round.id is null or v_round.status<>'open' then raise exception 'La ruleta no está disponible'; end if;
 select * into v_participant from event_participants where public_id=p_public_id and access_code=p_access_code; if v_participant.id is null then raise exception 'Acceso de participante inválido'; end if;
 if v_round.active_participant_id<>v_participant.id then raise exception 'No es tu turno'; end if;
 if exists(select 1 from event_roulette_spins where round_id=v_round.id) then raise exception 'Esta ronda ya tuvo un giro'; end if;
 select sum(weight) into v_total from event_roulette_inventory where room_id=v_round.room_id and active and (remaining_stock is null or remaining_stock>0);
 if coalesce(v_total,0)=0 then raise exception 'No hay premios disponibles'; end if; v_pick:=floor(random()*v_total)::int+1;
 select * into v_prize from (select i.*,sum(weight) over(order by position) cumulative from event_roulette_inventory i where room_id=v_round.room_id and active and (remaining_stock is null or remaining_stock>0)) q where cumulative>=v_pick order by cumulative limit 1 for update;
 if v_prize.remaining_stock is not null then update event_roulette_inventory set remaining_stock=remaining_stock-1 where id=v_prize.id; end if;
 insert into event_roulette_spins(round_id,participant_id,prize_key,prize_label,segment_index,is_winner) values(v_round.id,v_participant.id,v_prize.prize_key,v_prize.label,v_prize.position,v_prize.is_winner);
 update event_roulette_rounds set status='spun',result_prize_key=v_prize.prize_key,result_label=v_prize.label,result_segment_index=v_prize.position,is_winner=v_prize.is_winner,spun_at=now() where id=v_round.id;
 if v_prize.is_winner then update event_participants set registration_status='winner' where id=v_participant.id; end if;
 return jsonb_build_object('id',v_round.id,'status','spun','result_prize_key',v_prize.prize_key,'result_label',v_prize.label,'result_segment_index',v_prize.position,'is_winner',v_prize.is_winner,'active_participant_public_id',v_participant.public_id,'active_display_name',v_participant.display_name);
end $$;
grant execute on function public.spin_event_roulette(uuid,text,uuid) to anon,authenticated;
grant execute on function public.open_event_roulette_round(text),public.close_event_roulette_round(text),public.reset_event_roulette_round(text),public.reset_event_roulette_inventory(text),public.update_event_roulette_inventory(text,text,integer) to authenticated;
do $$ begin alter publication supabase_realtime add table public.event_roulette_rounds; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.event_roulette_inventory; exception when duplicate_object then null; end $$;
