-- Etapa 18: contingencia administrativa y recuperación segura.
-- Conserva historiales, respuestas, votos, giros, ganadores y recompensas.

create table if not exists public.event_contingency_logs (
 id bigint generated by default as identity primary key,
 room_id bigint not null references public.event_rooms(id) on delete cascade,
 admin_user_id uuid not null,
 action_key text not null,
 details jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);
alter table public.event_contingency_logs enable row level security;

create policy "event admins read contingency logs" on public.event_contingency_logs
for select to authenticated using (public.is_event_admin(auth.uid()));

create or replace function public.assert_event_admin()
returns void language plpgsql security definer set search_path=public as $$
begin
 if not public.is_event_admin(auth.uid()) then
  raise exception 'Acceso administrativo no autorizado';
 end if;
end $$;
revoke all on function public.assert_event_admin() from public;

create or replace function public.get_event_contingency_status(p_room_slug text default 'inauguracion-lihen')
returns jsonb language plpgsql security definer set search_path=public as $$
declare r event_rooms; result jsonb;
begin
 perform public.assert_event_admin();
 select * into r from event_rooms where slug=p_room_slug;
 if r.id is null then raise exception 'Sala no encontrada'; end if;
 select jsonb_build_object(
  'room_id',r.id,
  'room_open',r.room_open,
  'registration_open',r.registration_open,
  'event_status',r.event_status,
  'turn_status',r.turn_status,
  'active_participant_id',r.active_participant_id,
  'participants_active',(select count(*) from event_participants where room_id=r.id and registration_status='active'),
  'participants_connected',(select count(*) from event_participants where room_id=r.id and registration_status='connected'),
  'participants_waiting',(select count(*) from event_participants where room_id=r.id and registration_status='waiting'),
  'trivia_open',(select count(*) from event_trivia_rounds where room_id=r.id and status='open'),
  'word_open',(select count(*) from event_word_rounds where room_id=r.id and status='open'),
  'vote_open',(select count(*) from event_vote_rounds where room_id=r.id and status='open'),
  'flash_open',(select count(*) from event_flash_rounds where room_id=r.id and status='open'),
  'roulette_open',(select count(*) from event_roulette_rounds where room_id=r.id and status='open'),
  'checked_at',now()
 ) into result;
 return result;
end $$;
grant execute on function public.get_event_contingency_status(text) to authenticated;

create or replace function public.log_event_contingency(p_room_id bigint,p_action text,p_details jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path=public as $$
begin
 insert into event_contingency_logs(room_id,admin_user_id,action_key,details)
 values(p_room_id,auth.uid(),p_action,coalesce(p_details,'{}'::jsonb));
end $$;
revoke all on function public.log_event_contingency(bigint,text,jsonb) from public;

create or replace function public.close_all_event_game_rounds(p_room_slug text default 'inauguracion-lihen')
returns jsonb language plpgsql security definer set search_path=public as $$
declare r event_rooms; counts jsonb;
begin
 perform public.assert_event_admin();
 select * into r from event_rooms where slug=p_room_slug for update;
 if r.id is null then raise exception 'Sala no encontrada'; end if;
 update event_trivia_rounds set status='closed',closed_at=coalesce(closed_at,now()) where room_id=r.id and status='open';
 update event_word_rounds set status='closed',closed_at=coalesce(closed_at,now()) where room_id=r.id and status='open';
 update event_vote_rounds set status='closed',closed_at=coalesce(closed_at,now()) where room_id=r.id and status='open';
 update event_flash_rounds set status='closed',closed_at=coalesce(closed_at,now()) where room_id=r.id and status='open';
 update event_roulette_rounds set status='closed',closed_at=coalesce(closed_at,now()) where room_id=r.id and status='open';
 counts:=jsonb_build_object('message','Rondas abiertas cerradas','room_id',r.id);
 perform log_event_contingency(r.id,'close_all_rounds',counts);
 return counts;
end $$;
grant execute on function public.close_all_event_game_rounds(text) to authenticated;

create or replace function public.release_stuck_event_turn(p_room_slug text default 'inauguracion-lihen',p_participant_status text default 'waiting')
returns public.event_rooms language plpgsql security definer set search_path=public as $$
declare r event_rooms;
begin
 perform public.assert_event_admin();
 if p_participant_status not in('registered','connected','waiting','disabled','left') then raise exception 'Estado de retorno inválido'; end if;
 select * into r from event_rooms where slug=p_room_slug for update;
 if r.id is null then raise exception 'Sala no encontrada'; end if;
 if r.active_participant_id is not null then
  update event_participants set registration_status=p_participant_status where id=r.active_participant_id and registration_status='active';
 end if;
 update event_participants set registration_status=p_participant_status where room_id=r.id and registration_status='active';
 update event_rooms set active_participant_id=null,active_participant_public_id=null,active_display_name=null,active_modality=null,
  turn_status='idle',turn_started_at=null,turn_remaining_seconds=turn_duration_seconds,updated_at=now()
 where id=r.id returning * into r;
 perform log_event_contingency(r.id,'release_turn',jsonb_build_object('participant_status',p_participant_status));
 return r;
end $$;
grant execute on function public.release_stuck_event_turn(text,text) to authenticated;

create or replace function public.requeue_event_participants(p_room_slug text default 'inauguracion-lihen')
returns integer language plpgsql security definer set search_path=public as $$
declare r event_rooms; n integer;
begin
 perform public.assert_event_admin();
 select * into r from event_rooms where slug=p_room_slug;
 update event_participants set registration_status='waiting'
 where room_id=r.id and registration_status in('registered','connected','active');
 get diagnostics n=row_count;
 perform log_event_contingency(r.id,'requeue_participants',jsonb_build_object('updated',n));
 return n;
end $$;
grant execute on function public.requeue_event_participants(text) to authenticated;

create or replace function public.reopen_event_access(p_room_slug text default 'inauguracion-lihen')
returns public.event_rooms language plpgsql security definer set search_path=public as $$
declare r event_rooms;
begin
 perform public.assert_event_admin();
 update event_rooms set room_open=true,registration_open=true,event_status='registration',
  announcement='La sala fue recuperada. Puedes volver a ingresar.',updated_at=now()
 where slug=p_room_slug returning * into r;
 if r.id is null then raise exception 'Sala no encontrada'; end if;
 perform log_event_contingency(r.id,'reopen_access','{}'::jsonb);
 return r;
end $$;
grant execute on function public.reopen_event_access(text) to authenticated;

create or replace function public.recover_event_room_soft(p_room_slug text default 'inauguracion-lihen')
returns jsonb language plpgsql security definer set search_path=public as $$
declare r event_rooms; n integer;
begin
 perform public.assert_event_admin();
 perform close_all_event_game_rounds(p_room_slug);
 select * into r from release_stuck_event_turn(p_room_slug,'waiting');
 update event_participants set registration_status='waiting'
 where room_id=r.id and registration_status in('registered','connected','active');
 get diagnostics n=row_count;
 update event_rooms set room_open=true,event_status='waiting',active_activity='Sala recuperada',
  announcement='La sala fue recuperada. Espera nuevas instrucciones.',updated_at=now()
 where id=r.id returning * into r;
 perform log_event_contingency(r.id,'soft_recovery',jsonb_build_object('requeued',n));
 return jsonb_build_object('ok',true,'room_id',r.id,'requeued',n,'message','Recuperación suave completada');
end $$;
grant execute on function public.recover_event_room_soft(text) to authenticated;

create or replace function public.reset_event_operational_state(p_room_slug text default 'inauguracion-lihen')
returns jsonb language plpgsql security definer set search_path=public as $$
declare r event_rooms; n integer;
begin
 perform public.assert_event_admin();
 perform close_all_event_game_rounds(p_room_slug);
 select * into r from release_stuck_event_turn(p_room_slug,'waiting');
 update event_participants set registration_status='waiting',connected_at=null
 where room_id=r.id and registration_status in('registered','connected','active','waiting');
 get diagnostics n=row_count;
 update event_rooms set room_open=false,registration_open=false,event_status='preparing',active_activity=null,
  announcement='La sala se encuentra en preparación.',last_turn_modality=null,updated_at=now()
 where id=r.id returning * into r;
 perform log_event_contingency(r.id,'operational_reset',jsonb_build_object('participants_reset',n));
 return jsonb_build_object('ok',true,'participants_reset',n,'message','Estado operativo reiniciado sin borrar historial');
end $$;
grant execute on function public.reset_event_operational_state(text) to authenticated;

create or replace view public.event_contingency_logs_admin as
select l.id,l.action_key,l.details,l.created_at,a.display_name admin_name,r.slug room_slug
from event_contingency_logs l
join event_rooms r on r.id=l.room_id
left join admin_profiles a on a.user_id=l.admin_user_id;
grant select on public.event_contingency_logs_admin to authenticated;
